//! Streaming events emitted by the agent loop.
//!
//! [`AgentEvent`] is the transient, in-memory event stream that the
//! runtime pushes to consumers (TUI, logger, tests). For durable,
//! JSONL-persisted records see [`crate::SessionEntry`].
//!
//! All variants are **struct variants**, never newtype variants, because
//! the `#[serde(tag = "type")]` representation requires field names.

use serde::{Deserialize, Serialize};

use crate::ids::{RunId, SessionId, Timestamp, ToolCallId};

/// Current schema version stamped on durable records.
///
/// Bumped whenever an on-disk format breaks compatibility. Keep this in
/// sync with the persistence layer's reader.
pub const SCHEMA_VERSION: u32 = 1;

/// One frame on the live event stream.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "type", rename_all = "PascalCase")]
pub enum AgentEvent {
    /// A new run has begun. Carries the run/session ids and start time.
    RunStarted {
        run_id: RunId,
        session_id: SessionId,
        started_at: Timestamp,
    },
    /// The model invocation for this run has started.
    ModelStarted,
    /// Incremental text output from the assistant.
    TextDelta { text: String },
    /// Incremental reasoning/thinking output from the assistant.
    ReasoningDelta { text: String },
    /// A tool invocation has been dispatched.
    ToolStarted {
        call_id: ToolCallId,
        name: String,
        args: serde_json::Value,
    },
    /// A chunk of tool output, tagged with which stream it came from.
    ToolOutput {
        call_id: ToolCallId,
        stream: ToolStream,
        chunk: Vec<u8>,
    },
    /// A tool invocation has finished, successfully or not.
    ToolFinished {
        call_id: ToolCallId,
        result: ToolOutcome,
    },
    /// The model invocation for this run has finished.
    ModelFinished {
        usage: Usage,
        stop_reason: StopReason,
    },
    /// The run finished cleanly.
    RunFinished { message: String },
    /// The run was cancelled by the user or supervisor.
    RunCancelled,
    /// The run failed with a structured error.
    ///
    /// **Field order is load-bearing** — it must match spec §9 exactly:
    /// `code`, then `retryable`, then `message`.
    RunFailed {
        code: ErrorCode,
        retryable: bool,
        message: String,
    },
}

/// Which substream of a tool's output a chunk came from.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ToolStream {
    /// Standard output of the child process.
    Stdout,
    /// Standard error of the child process.
    Stderr,
}

/// Terminal outcome of a tool invocation.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum ToolOutcome {
    /// The tool returned successfully.
    Success { output: String, truncated: bool },
    /// The tool returned an error result.
    Error {
        code: ErrorCode,
        message: String,
        truncated: bool,
    },
}

/// Token accounting for a single model invocation.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Usage {
    /// Tokens consumed by the prompt (input side).
    pub input_tokens: u32,
    /// Tokens generated by the model (output side).
    pub output_tokens: u32,
}

/// Why the model stopped generating.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "PascalCase")]
pub enum StopReason {
    /// The model chose to end its turn.
    EndTurn,
    /// The model emitted one or more tool calls.
    ToolUse,
    /// The model hit the configured output token cap.
    MaxTokens,
    /// Generation was cancelled mid-flight.
    Cancellation,
    /// The provider returned an error.
    Error,
}

/// Structured error code.
///
/// Serialises as a plain JSON string via `#[serde(transparent)]`, e.g.
/// `ErrorCode("stream_invalid")` → `"stream_invalid"`.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(transparent)]
pub struct ErrorCode(pub String);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::{new_id, SessionId, ToolCallId};

    fn run_started() -> AgentEvent {
        AgentEvent::RunStarted {
            run_id: RunId(new_id()),
            session_id: SessionId(new_id()),
            started_at: Timestamp::now(),
        }
    }

    #[test]
    fn schema_version_is_one() {
        assert_eq!(SCHEMA_VERSION, 1);
    }

    #[test]
    fn error_code_serialises_transparently() {
        let code = ErrorCode("stream_invalid".to_string());
        let json = serde_json::to_string(&code).expect("serialize");
        assert_eq!(json, "\"stream_invalid\"");
        let back: ErrorCode = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, code);
    }

    #[test]
    fn tool_stream_is_lowercase() {
        let json = serde_json::to_string(&ToolStream::Stdout).expect("serialize");
        assert_eq!(json, "\"stdout\"");
        let json = serde_json::to_string(&ToolStream::Stderr).expect("serialize");
        assert_eq!(json, "\"stderr\"");
        // Round-trip too.
        let back: ToolStream = serde_json::from_str("\"stdout\"").expect("deserialize");
        assert_eq!(back, ToolStream::Stdout);
    }

    #[test]
    fn every_agent_event_variant_round_trips() {
        let events = vec![
            AgentEvent::RunStarted {
                run_id: RunId(new_id()),
                session_id: SessionId(new_id()),
                started_at: Timestamp::now(),
            },
            AgentEvent::ModelStarted,
            AgentEvent::TextDelta { text: "hi".into() },
            AgentEvent::ReasoningDelta {
                text: "thinking".into(),
            },
            AgentEvent::ToolStarted {
                call_id: ToolCallId(new_id()),
                name: "shell".into(),
                args: serde_json::json!({"cmd": "ls"}),
            },
            AgentEvent::ToolOutput {
                call_id: ToolCallId(new_id()),
                stream: ToolStream::Stdout,
                chunk: b"hello\n".to_vec(),
            },
            AgentEvent::ToolFinished {
                call_id: ToolCallId(new_id()),
                result: ToolOutcome::Success {
                    output: "ok".into(),
                    truncated: false,
                },
            },
            AgentEvent::ModelFinished {
                usage: Usage {
                    input_tokens: 5,
                    output_tokens: 2,
                },
                stop_reason: StopReason::EndTurn,
            },
            AgentEvent::RunFinished {
                message: "done".into(),
            },
            AgentEvent::RunCancelled,
            AgentEvent::RunFailed {
                code: ErrorCode("boom".into()),
                retryable: true,
                message: "kaboom".into(),
            },
        ];
        for event in events {
            let json = serde_json::to_string(&event).expect("serialize");
            let back: AgentEvent = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(event, back);
        }
    }

    #[test]
    fn run_failed_field_order_matches_spec() {
        // The serialized JSON must put `code` before `retryable` before
        // `message`; spec §9 pins this exact order. We check via the
        // Rust struct field order (which is what spec §9 actually
        // constrains — JSON key order is not guaranteed across serde
        // versions because serde_json::Map is BTreeMap-ordered).
        let event = AgentEvent::RunFailed {
            code: ErrorCode("x".into()),
            retryable: false,
            message: "m".into(),
        };
        let value: serde_json::Value = serde_json::to_value(&event).expect("to_value");
        let obj = value.as_object().expect("object");
        assert_eq!(obj["type"], "RunFailed");
        assert_eq!(obj["code"], "x");
        assert_eq!(obj["retryable"], false);
        assert_eq!(obj["message"], "m");
        // Also assert the struct field order is what we documented,
        // by round-tripping through a typed alias that pins the order.
        #[derive(serde::Deserialize)]
        struct _Order {
            #[allow(dead_code)]
            code: String,
            #[allow(dead_code)]
            retryable: bool,
            #[allow(dead_code)]
            message: String,
        }
        let _typed: _Order = serde_json::from_value(value).expect("from_value");
    }

    #[test]
    fn run_started_has_run_started_tag() {
        let event = run_started();
        let value = serde_json::to_value(&event).expect("to_value");
        assert_eq!(value["type"], "RunStarted");
    }
}
